### ISSUE TITLE
Pages Wont Load :sob: :sob: :sob: :sob: :sob: :sob: :sob: 

### ISSUE THREAD

**Issue by FoxMoss** [Thesecondalthowcool/Dynamic-Static-Version#1]
WHYDID IT BLOCKED WHEN IT WAS SUPPOSED TO BE STATIC :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: !!!!11!!!11!

**Comment by Thesecondalthowcool** [comment]
Cause the bare server is not turned on. Just go to ilovebears.eduiscooltbh.eu.org and wait for to turn on. Once your down with that you can use the proxy.
