### ISSUE TITLE
the bare server is blocked :sob:

### ISSUE THREAD

**Issue by FoxMoss** [Thesecondalthowcool/Dynamic-Static-Version#2]
IDK WHERE THE ISSUE WHENT BUT WHEN I WENT TO THE SITE YOU SAID IT WAS BLOCKED :angry: :angry: :angry: :angry: :angry: :angry: :angry: :angry:  WHY DOESNT MAKING A NEW WEBSITE WORK :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob:

**Comment by Thesecondalthowcool** [comment]
ok
